#!/bin/sh
#purpose: run PSSM 
#author: Avdesh

psiblast_path="/home1/presentation/DBase/BLAST/ncbi-blast-2.2.28+/bin";
nr_database_path="/home1/presentation/DBase/BLAST/ncbi-blast-2.2.28+/bin/nr/nr";

input_path="../input"
fasta="../input/fasta";
pssm_output_file_path="../pssmout";

for file in `cat $input_path/pdbList.txt`;
do 
	#===========================================================================================================
	#Run PSI-BLAST to generate PSSM
	
	if [ -f ../pssmout/$file.mat ];
	then
		printf "PSSM already exists!!\n";
	else
		printf "running PSI-BLAST...";
		$psiblast_path/psiblast -query $fasta/$file.fasta -db $nr_database_path -out $pssm_output_file_path/$file.out -num_iterations 3 -num_threads 16 -out_ascii_pssm $pssm_output_file_path/$file.mat;
		printf "...DONE!!!\n";
	fi
	#===========================================================================================================
done